version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-greenglow}
      POSTGRES_USER: ${POSTGRES_USER:-greenglow}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change-me}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://greenglow:change-me@db:5432/greenglow}
      NODE_ENV: production
      PORT: 5000
      JWT_SECRET: ${JWT_SECRET}
      SEED_ON_START: ${SEED_ON_START:-true}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    networks:
      - default

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "8082:80"   # http://51.83.33.20:8082
    networks:
      caddy_net:
        aliases:
          - greenglow-web
      default: {}

volumes:
  db_data:

networks:
  default: {}
  caddy_net:
    external: true
